# Basics of NumPY

In [4]:
import numpy as np

In [6]:
a=np.array([1,2,3,4])

In [7]:
print(a)

[1 2 3 4]


In [9]:
b=np.array([2,3,6,8])
print(b)


[2 3 6 8]


In [10]:
#print the shape of array
print(a.shape)
print(b.shape)

(4,)
(4,)


In [11]:
#type of array
print(type(a))

<class 'numpy.ndarray'>


In [12]:
#print zero ones and eye matrix

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((4,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#mathematical function

In [17]:
c=a+b
print(c)

[ 3  5  9 12]


In [21]:
d=a*b
e=a-b
f=a/b
g=a**b
print(d)
print(e)
print(f)
print(g)

[ 2  6 18 32]
[-1 -1 -3 -4]
[0.5        0.66666667 0.5        0.5       ]
[    1     8   729 65536]


# stacking in Array

In [22]:
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [2, 3, 6, 8]])

In [23]:
np.stack((a,b),axis=1)

array([[1, 2],
       [2, 3],
       [3, 6],
       [4, 8]])

# to reshape the Array

In [30]:
a=a.reshape((4,1))
print(a)

[[1]
 [2]
 [3]
 [4]]
