# Numpy Random and Statistic

In [1]:
import numpy as np

In [10]:
a=np.random.randn(2,3)

In [ ]:
a=np.random.randn(2,3)

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [15]:
#find the min value
print(np.min(a)) #find from array
print(np.min(a,axis=0)) #fing from collum

1
[1 2 3 4]


In [17]:
print(np.mean(a)) #find from array
print(np.mean(a,axis=0)) #fing from collum
print(np.mean(a,axis=1)) #fing from row

4.5
[3. 4. 5. 6.]
[2.5 6.5]


In [18]:
print(np.std(a)) #find standard deviation

2.29128784747792


In [19]:
print(np.var(a)) #find variance from array

5.25


[[-0.20005553 -1.95250623 -0.46765037]
 [ 0.98572073  0.33056398  1.17457815]]
